#!/usr/bin/env ruby

exit 0 unless ENV['SITE_USERNAME'] && ENV['SITE_PASSWORD']

require 'webrick'

file = "#{ENV['HOME']}/config/htpasswd"
htpasswd = WEBrick::HTTPAuth::Htpasswd.new(file)
htpasswd.set_passwd(nil, ENV['SITE_USERNAME'], ENV['SITE_PASSWORD'])
htpasswd.flush
